version: '3.8'

services:
  simanis-core-web-next:
    build:
      context: .
      dockerfile: Dockerfile
    image: simanis-core-web-next
    container_name: simanis-core-web-next
    # network_mode: host
    ports:
      - "80:3000"
    restart: unless-stopped

networks:
  default:
    name: simanis