name: core-web-next deploy to EKS
on:
    push: 
        branches: main
    pull_request:
        branches: main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Install kubectl
              uses: azure/setup-kubectl@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
                aws-region: ${{ vars.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: add env
              run: |
                cat <<EOT >> .env
                NEXT_PUBLIC_BACKEND_URL="http://si-manis.my.id:5050"
                GROQ_API_KEY="${{secrets.GROQ_API_KEY}}"
                
                DATABASE_URL="${{secrets.DATABASE_URL}}"
                
                PAYLOAD_SECRET="${{ secrets.PAYLOAD_SECRET}}"
                PAYLOAD_PUBLIC_SERVER_URL="http://si-manis.my.id:3000"
                
                REVALIDATION_KEY="${{ secrets.REVALIDATION_KEY}}"
                NEXT_PRIVATE_REVALIDATION_KEY="${{ secrets.NEXT_PRIVATE_REVALIDATION_KEY}}"
                
                S3_ACCESS_KEY_ID="AKIA5OETRXDHZUXE3F4J"
                S3_SECRET_ACCESS_KEY="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"
                S3_REGION="ap-southeast-1"
                S3_ENDPOINT="s3.ap-southeast-1.amazonaws.com"
                S3_BUCKET="simanis"
                NEXT_PUBLIC_S3_HOSTNAME="simanis.s3.ap-southeast-1.amazonaws.com"
                NEXT_PUBLIC_UPLOAD_PREFIX= # This is optional, should be a-z without /
                EOT

            - name: Build, tag, and push docker image to amazon ecr
              env: 
                REGISTRY: ${{steps.login-ecr.outputs.registry}}
                REPOSITORY: simanis-core-web-next
                IMAGE_TAG: latest
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

            - name: Update kube config
              run: aws eks update-kubeconfig --name simanis-cluster

            - name: Deploy to EKS
              run: |
                kubectl apply -f k8s-simanis.yaml